
site_description: Chartiful - Modern JavaScript SVG Charts.
root_domain: chartiful.io
theme: jekyll-theme-midnight

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
